version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: notes
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  app:
    image: 192.168.1.18:5000/cloud-notes-backend:latest
    ports:
      - "8080:8080"
    pull_policy: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/notes
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

volumes:
  postgres_data: